source/BruktBok/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace BruktBok.Models
{
    /// <summary>
    /// model for items to be sold on the website.
    /// </summary>
    
    public class Book
    {
      
        public Book(){}
        public Book(string title, string summary,decimal price, int departmentId )
        {
            Title = title;
            Summary = summary;
            Price = price; ;
            DepartmentId = departmentId;
            DepartmentBooks = new List<DepartmentBook>();
        }
        public int Id { get; set; }
        
        [Required]
        [Display(Name = "Tittel")]
        public string Title { get; set; }
        
        [Required]
        [Display(Name = "Sammendrag")]
        public string Summary { get; set; }

        [Required] [DataType(DataType.Date)]
        public string Posted { get; set; } = DateTime.Now.ToString("g")/*("dd.MM.yyyy")*/;
       
        [Required]
        [DataType(DataType.Currency)]
        [Display(Name = "Pris")]
        public decimal Price { get; set; }
        
        [Display(Name = "Beskrivelse")]
        public string Description { get; set; }
        // image variable
        [DataType(DataType.ImageUrl)]
        [Display(Name="Bilde")]
         public string ImageUrl { get; set; }
         
      
         public byte[] Content { get; set; }
        //owner
        public ApplicationUser ApplicationUser { get; set; }
       
        public string ApplicationUserId { get; set; }
        
        public  Department Department { get; set; }
       
        [Display(Name = "Studieprogram")]
        public  int DepartmentId { get; set; }
        // Departments this book belongs
        public List<DepartmentBook> DepartmentBooks { get; set; } = new List<DepartmentBook>();
    }
}

source/BruktBok/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BruktBok.Data;
using BruktBok.Models;
using BruktBok.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using static BruktBok.Models.ISendPost;


namespace BruktBok.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _um;
        private readonly IFileUpload _fileUpload;

        private ISendPost _sendPost;

        /// dependency for file uploader.
        private IWebHostEnvironment _env;

        public BooksController(ApplicationDbContext context, UserManager<ApplicationUser> um,
            IWebHostEnvironment env, IFileUpload fileUpload, ISendPost sendPost)
        {
            _context = context;
            _um = um;
            _env = env;
            _fileUpload = fileUpload;
            _sendPost = sendPost;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchString)
        {
            var listOfBooks = from m in _context.Books
                select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                listOfBooks = listOfBooks.Where(s => s.Title.Contains(searchString));
            }


            var books = new BookOverView
            {
                Books = await
                    listOfBooks.ToListAsync()
            };

            return View(books);
        }

        [Produces("application/json")]
        [HttpGet("getbooks")]
        public IActionResult GetBooks()

        { 
            var book = from m in _context.Books
                select m;

            try
            {
                string term = HttpContext.Request.Query["term"].ToString();
                var bookTitle = book.Where(p => p.Title.StartsWith(term)).Select(p => p.Title).ToList();
                return Ok(bookTitle);
            }
            catch
            {
                return BadRequest();
            }
        }


        
        [HttpGet]
        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (book == null)
            {
                return NotFound();
            }


            return View(book);
        }

        //GET;Books/Get Users Books
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> UserBook()
        {
            var user = _um.GetUserId(User);
            var userBooks = _context.Books.Where(book => book.ApplicationUserId == user)
                .OrderByDescending(bk => bk.Id);

            var books = new BookOverView {Books = await userBooks.ToListAsync()};

            return View(books);
        }

        // GET: Books/Create
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            var departments = new BookOverView();
            foreach (var department in _context.Departments)
            {
                departments.DepartmentList.Add(new SelectListItem
                {
                    Text = department.Name, Value = department.DepartmentId.ToString()
                });
            }

            ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            //ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name").ToList();
            return View(departments);
        }


        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Contact(ContactSeller contactSeller, int id)
        {
            var book = await _context.Books
                .Include(b => b.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (ModelState.IsValid)
            {

                await _sendPost.SendEmail(contactSeller,book.ApplicationUser.Email,"");


                Console.Beep();
            }

            return RedirectToAction(nameof(Contact));
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Title,Summary,Description,Price,Content,DepartmentId,ApplicationUserId")]
            Book book, IFormFile file)
        {
            /*Image,*/
            if (ModelState.IsValid)
            {
                var userId = _um.GetUserId(User);
                _context.ApplicationUsers.Find(userId).UserBooks.Add(book);
                book.ApplicationUserId = userId;


                book.DepartmentBooks.Add(new DepartmentBook {BookId = book.Id, DepartmentId = book.DepartmentId});
                if (file != null)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await file.CopyToAsync(memoryStream);

                        // Upload the file if less than 2 MB
                        if (memoryStream.Length < 2097152)
                        {
                            book.Content = memoryStream.ToArray();
                            _context.Books.Add(book);
                            await _context.SaveChangesAsync();
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            ModelState.AddModelError("File", "The file is too large.");
                        }
                    }
                }
            }

            /*if (ModelState.IsValid)
            {
                var userId = _um.GetUserId(User);
                _context.ApplicationUsers.Find(userId).UserBooks.Add(book);
                book.ApplicationUserId = userId;
                
                
                book.DepartmentBooks.Add(new DepartmentBook {BookId = book.Id, DepartmentId = book.DepartmentId});
                if (file != null)
                {
                    var filename = file.FileName;
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", filename);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    book.ImageUrl = filename;
                }


                _context.Books.Add(book);

                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }*/

            ViewData["ApplicationUserId"] =
                new SelectList(_context.ApplicationUsers, "Id", "Id", book.ApplicationUserId);
            return View();
        }


        [Authorize]
        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);

            if (book == null)
            {
                return NotFound();
            }

            if (!User.IsInRole("Admin") && (_um.GetUserId(User) != book.ApplicationUserId))
            {
                return RedirectToAction("Index");
            }

            ViewData["ApplicationUserId"] =
                new SelectList(_context.ApplicationUsers, "Id", "Id", book.ApplicationUserId);
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "DepartmentId", "Name").ToList();
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,Title,Summary,Description,Price,Content,DepartmentId,ApplicationUserId")]
            Book book, IFormFile file)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = _um.GetUserId(User);
                    book.ApplicationUserId = user;
                   // _fileUpload.uploadImage(file);
                   
                    if (file != null)
                    {
                       // book.ImageUrl = file.FileName;
                        
                        using (var memoryStream = new MemoryStream())
                        {
                            await file.CopyToAsync(memoryStream);

                            // Upload the file if less than 2 MB
                            if (memoryStream.Length < 2097152)
                            {
                                book.Content = memoryStream.ToArray();
                                
                            }else
                            {
                                ModelState.AddModelError("File", "The file is too large.");
                            }
                        }

source/BruktBok/Views/Books/Contact.cshtml
@model ContactSeller

@{
    ViewBag.Title = "Contact";

}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato:300,400,700'>
<div class="container">

    <div class="row">

      <div class="col-lg-8 col-lg-offset-2">

        
        <form id="contact-form" method="post" asp-controller="Books" asp-action="Contact" role="form">

        <div class="messages"></div>

        <div class="controls">

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="form_name">Firstname *</label>
                <input   asp-for="Name" id="form_name" type="text" name="name" class="form-control" placeholder="Please enter your firstname *" required="required" data-error="Firstname is required.">
                <div class="help-block with-errors"></div>
              </div>
            </div>
            
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="form_email">Email *</label>
                <input asp-for="Email" id="form_email" type="email" name="email" class="form-control" placeholder="Please enter your email *" required="required" data-error="Valid email is required.">
                <div class="help-block with-errors"></div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="form_phone">Phone</label>
                <input asp-for="PhoneNumber" id="form_phone" type="tel" name="phone" class="form-control" placeholder="Please enter your phone">
                <div class="help-block with-errors"></div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="form_message">Message *</label>
                  <textarea  asp-for="Message" id="form_message" name="message" class="form-control" placeholder="Message for me *" rows="4" required data-error="Please,leave us a message.">

</textarea>
                <div class="help-block with-errors"></div>
              </div>
            </div>
            <div class="col-md-12">
              <input type="submit" class="btn btn-success btn-send" value="Send message">
            </div>
          </div>
         
        </div>

        </form>

      </div>

    </div>

  </div>
   <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'></script>
<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.9/validator.min.js'></script>

source/BruktBok/Views/Books/Create.cshtml
@addTagHelper*,Microsoft.AspNetCore.Mvc.TagHelpers
@using BruktBok.Data
@model BookOverView
@inject ApplicationDbContext DbContext
@{
    ViewData["Title"] = "Create";
}

<h1>Register a Book</h1>

<hr/>
<div class="row align-content-center">
    <div class="col-md-4">
        @* this form has multipat/form-data to be able to handle uploading a file.*@
        <form asp-controller="Books" enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="@Model.Book.Title" class="control-label"></label>
                <input asp-for="@Model.Book.Title" class="form-control"/>
                <span asp-validation-for="@Model.Book.Title" class="text-danger"></span>

              
            </div>
            <div class="form-group">
                <label asp-for="@Model.Book.Summary" class="control-label"></label>
                <input asp-for="@Model.Book.Summary" class="form-control"/>
                <span asp-validation-for="@Model.Book.Summary" class="text-danger"></span>

              
            </div>
            <div class="form-group">
                <label asp-for="@Model.Book.Description" class="control-label"></label>
                <textarea asp-for="@Model.Book.Description" class="form-control" rows="3"></textarea>
                <span asp-validation-for="@Model.Book.Description" class="text-danger"></span>
                
            </div>
            <div class="form-group">
                <label asp-for="@Model.Book.Price" class="control-label"></label>
                <input asp-for="@Model.Book.Price" class="form-control"/>
                <span asp-validation-for="@Model.Book.Price" class="text-danger"></span>
             
            </div>
            <div class="form-group">
                <label asp-for="@Model.Book.DepartmentId" class="control-label"></label>
                <select asp-for="@Model.Book.DepartmentId" class="form-control" id="select-department"
                        asp-items="@Model.DepartmentList">
                   
                    <option value="department" selected disabled>-- select Studieprogram--</option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label"> Upload Image( only JPEG format)</label>
                <input type="file" id="file" name="file" class="form-control" runat="server" accept=".png,.jpg,.jpeg,.gif"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

source/BruktBok/Views/Books/Delete.cshtml
@model BruktBok.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Posted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Posted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

source/BruktBok/Views/Books/Details.cshtml
@model BruktBok.Models.Book
@using BruktBok.Data
@using Microsoft.AspNetCore.Identity
@inject ApplicationDbContext DbContext
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">

                @{
                    if (Model.Content != null)
                    {
                        <img src="data:image;base64,@System.Convert.ToBase64String(Model.Content)" class="card-img-top" alt="..."/>
                    }
                }

                @* <img class="image" src="@Url.Content("~/Images/" + Model.ImageUrl)" alt="@Model.Title"/> *@

            </div>
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                <div class="container" style="border-bottom:1px solid black">
                    <h2> @Html.DisplayFor(model => model.Title)</h2>
                </div>
                <hr>
                <ul class="container details">
                    <li>
                        <p>
                            <span class="fas fa-book" style="width:50px;">
                            </span>@Html.DisplayFor(model => model.Summary)</p>
                    </li>

                    <li>
                        <p>
                            <span class="fas fa-wallet" style="width:50px;">
                            </span>@Html.DisplayFor(model => model.Price)</p>
                    </li>

                    <li>
                        <p>
                            <span class="far fa-calendar-alt" style="width:50px;">

                            </span>@Html.DisplayFor(model => model.Posted)</p>
                    </li>
                    <li>
                        <p>
                            <h2>Beskrivelse</h2>
                            @Html.DisplayFor(model => model.Description)
                        </p>
                    </li>
                    <li>
                        <p>
                            <span class="glyphicon glyphicon-map-marker one" style="width:50px;">

                            </span>Grimstad
                        </p>
                    </li>

                </ul>
            </div>

        </div>
        <br>
        <br>
        <div>
            @{
                if (SignInManager.IsSignedIn(User))
                {
                    try
                    {
                        var user = await UserManager.GetUserAsync(User);
                        var userId = user.Id;
                        var bookOwner = Model.ApplicationUserId;

                        if (bookOwner == userId)
                        {
                            // this returns the edit and delete view only for the owner of the book
                            <a asp-controller="Books" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                            <a asp-controller="Books" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                        }
                        else
                        {
                            <a href="@Url.Action("Contact", "Books", new {id = Model.Id})">

                                <a class="btn btn-primary" href="@Url.Action("Contact", "Books", new {id = Model.Id})">Contact Seller</a>|
                            </a>
                            <a class="btn btn-primary" asp-controller="Home" asp-action="PaymentForm" asp-route-BookID="@Model.Id">Buy the book</a>
                        }
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                        throw;
                    }
                }
                else
                {
                    <a href="@Url.Action("Contact", "Books", new {id = Model.Id})">

                        <a class="btn btn-primary" href="@Url.Action("Contact", "Books", new {id = Model.Id})">Contact Seller</a>|
                    </a>

                    @*<a asp-controller="Books" asp-action="Details" asp-route-id="@Model.Id">Details</a>*@
                    <a class="btn btn-primary" asp-controller="Home" asp-action="PaymentForm" asp-route-BookID="@Model.Id">Buy the book</a>
                }

            }
            @*<a href="@Url.Action("Contact", "Books", new {id = Model.Id})">

                <a class="btn btn-primary" href="@Url.Action("Contact", "Books", new {id = Model.Id})">Contact Seller</a>|
            </a>|*@

            <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Back to List</a>

        </div>

    </div>

</div>


<script >



</script>

source/BruktBok/Views/Books/Edit.cshtml
@model BruktBok.Models.Book

@{
    ViewData["Title"] = "Edit";
}

<h1 xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">Edit</h1>

<h4>Book</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Title" class="control-label">

                </label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger">

                </span>
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label">
                </label>
                <input asp-for="Summary" class="form-control"/>
                <span asp-validation-for="Summary" class="text-danger">

                </span>
            </div>
            <div class="form-group">

                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label">

                </label>
                <input asp-for="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger">

                </span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label">

                </label>
                <select asp-for="DepartmentId" class="form-control" id="select-department"
                        asp-items="@ViewBag.DepartmentId">
                    <option value=" " selected disabled>-- select department--</option>
                </select>
            </div>
            <div class="form-group">
                <label class="control-label"> Upload Image( only JPEG format)</label>
                <input type="file" id="file" name="file" class="form-control" runat="server" accept=".png,.jpg,.jpeg,.gif"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

source/BruktBok/Views/Books/Index.cshtml
@using BruktBok.Data
@using Microsoft.AspNetCore.Identity
@model BookOverView
@inject ApplicationDbContext DbContext
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@*We are using partial view her*@
<div class="column-layout">
    <div class="man-column">
<div class="card-deck">
            <div class="container container mt-4 mb-5">
                <div class="row">
                    @foreach (var p in Model.Books)
                    {
                        <partial name="_homePagePartial" model="p"/>
                    }
                </div>
            </div>  </div>
            </div>
 </div>




  

source/BruktBok/Views/Books/UserBook.cshtml
@using BruktBok.Data
@using Microsoft.AspNetCore.Identity
@model BookOverView
@inject ApplicationDbContext DbContext
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager

<table class="table">
    <div> My listed Books</div>
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Book.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Book.Summary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Book.Posted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Book.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Book.ImageUrl)
        </th>
    </tr>
    </thead>
    <tbody>

    @foreach (var book in Model.Books)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => book.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => book.Summary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => book.Posted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => book.Price)
            </td>
            <td>
                <div>
                    @{
                        if (book.Content != null)
                        {
                            <img src="data:image;base64,@System.Convert.ToBase64String(book.Content)" class="card-img-top" alt="..."/>
                        }
                    }
                   
                    @* <img src="@Url.Content("~/Images/" + book.ImageUrl)" style="width:30px;height:30px" alt="@book.Title"/> *@
                </div>
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@book.Id">Details</a> |
                <a asp-action="Edit" asp-route-id="@book.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@book.Id">Delete</a>
            </td>
        </tr>
    }

    </tbody>
</table>